/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qbsoykxjzmmrvdcgmqts"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFic295a3hqem1tcnZkY2dtcXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MjAwNTYsImV4cCI6MjA4NzI5NjA1Nn0.xeOVFuzxjG-GuPa1WppeAj-2UeFUJOyeldZHyQsAD5k"